// Copyright 2021-2026 Naotsun. All Rights Reserved.

#include "PulldownBuilder/Assets/PulldownContentsDelegates.h"

namespace PulldownBuilder
{
	FPulldownContentsDelegates::FOnAllPulldownContentsLoaded FPulldownContentsDelegates::OnAllPulldownContentsLoaded;
	FPulldownContentsDelegates::FOnPulldownContentsLoaded FPulldownContentsDelegates::OnPulldownContentsLoaded;
	FPulldownContentsDelegates::FOnDetailCustomizationRegistered FPulldownContentsDelegates::OnDetailCustomizationRegistered;
	FPulldownContentsDelegates::FOnDetailCustomizationUnregistered FPulldownContentsDelegates::OnDetailCustomizationUnregistered;
	FPulldownContentsDelegates::FOnPulldownRowAdded FPulldownContentsDelegates::OnPulldownRowAdded;
	FPulldownContentsDelegates::FOnPulldownRowRemoved FPulldownContentsDelegates::OnPulldownRowRemoved;
	FPulldownContentsDelegates::FOnPulldownRowRenamed FPulldownContentsDelegates::OnPulldownRowRenamed;
	FPulldownContentsDelegates::FOnPulldownContentsSourceChanged FPulldownContentsDelegates::OnPulldownContentsSourceChanged;
	FPulldownContentsDelegates::FOnPulldownStructTypeChangePending FPulldownContentsDelegates::OnPulldownStructTypeChangePending;
	FPulldownContentsDelegates::FOnPulldownStructTypeChangeCommitted FPulldownContentsDelegates::OnPulldownStructTypeChangeCommitted;
}
